### ISSUE TITLE
webpack --config webpack.config.js hangs

### ISSUE THREAD

**Issue by rkstar** [roman01la/react-native-babel#1]
i downloaded the zip of your repo, then tried the webpack command and it just hangs with this output:

Macintosh:react-native-babel rkstar$ webpack --config webpack.config.js 
Hash: 65cb6786179d1448a4d0
Version: webpack 1.7.3
Time: 633ms
       Asset     Size  Chunks             Chunk Names
index.ios.js  11.3 kB       0  [emitted]  main
    + 48 hidden modules

what's going on here?

**Comment by roman01la** [comment]
Here webpack runs in watch mode. This means it will compile every time you make a change in your code.

**Comment by sabarasaba** [comment]
Dont know if its related or not, but I get:

![screen shot 2015-03-30 at 15 44 44](https://cloud.githubusercontent.com/assets/1191206/6898787/fcc77a60-d6f3-11e4-827a-8810d226cb06.png)

And there are no errors/warnings at all (even in xcode). Any idea of what it might be ? @rkstar do you get the same thing ?

**Comment by sabarasaba** [comment]
Duh, ignore me. I fixed it by changing jsCodeLocation from AppDelegate.m to point to localhost instead of my computers ip.

**Comment by roman01la** [comment]
Yeah, that's what everyone should check before run the project.

**Comment by sabarasaba** [comment]
You should definitely add it to the readme file ! :panda_face:

**Comment by roman01la** [comment]
True, thanks! :+1:
