### ISSUE TITLE
Support for React Native 0.17.0

### ISSUE THREAD

**Issue by jhabdas** [roman01la/react-native-babel#10]
RN `0.17.0` dropped earlier today ([release docs](https://github.com/facebook/react-native/releases/tag/v0.17.0)). Any plans to move this seed forward to provide support? If you're looking for an upgrade path [here's a way](https://github.com/jhabdas/react-native-webpack-starter-kit/commit/ee61a131ed09c5a0fa83f61c0fa3b50791cf4b9f). It requires hacking on some iOS project files created by RN but it's doable.

**Comment by niftylettuce** [comment]
@jhabdas Are you sure this work with `npm run webpack`?

Errors for me (I'm not using that ignore thing):

```log
Module not found: Error: Cannot resolve module 'image' in
Module not found: Error: Cannot resolve module 'ActivityIndicatorIOS'
etc.
```

**Comment by jhabdas** [comment]
I'm not sure what commands are available in this kit. But with all the Stargazers I want to be sure some traffic moves towards something the more robust, as this kit was inspirational in my related work.

**Comment by niftylettuce** [comment]
https://gist.github.com/alexesDev/071f8935c82ca87a5b46

**Comment by roman01la** [comment]
Hello. I'm not using this at the moment. Feel free to submit a PR and reopen this issue.
