### ISSUE TITLE
How did you generate ignore-modules?  Is it up to date with RN 17?

### ISSUE THREAD

**Issue by niftylettuce** [roman01la/react-native-babel#11]

**Comment by niftylettuce** [comment]
https://gist.github.com/alexesDev/071f8935c82ca87a5b46

**Comment by roman01la** [comment]
I'm not using the code here at the moment. It may be incompatible with newer RN releases. You can check the code in [dep-graph](https://github.com/roman01la/react-native-babel/blob/dep-graph/webpack-watch.js) branch.
