### ISSUE TITLE
Embedded images cause webpack to fail

### ISSUE THREAD

**Issue by mbrio** [roman01la/react-native-babel#2]
Since React Native's packager uses `require('image!some_image_name')` to embed image resources, some way of ignoring the *image!* module within webpack is needed. Without ignore *image!* modules webpack fails with *Cannot resolve module 'image'*.

**Comment by joewood** [comment]
Can you not include the `image!` in the regex for externals in the webconfig?
```javascript
 externals: [/image\!|React|ActivityIndicatorIOS|DatePickerIOS|Image|ListView|MapView|NavigatorIOS|PickerIOS|Navigator|ScrollView|SliderIOS|SwitchIOS|TabBarIOS|Text|TextInput|TouchableHighlight|TouchableOpacity|TouchableWithoutFeedback|View|WebView|AlertIOS|Animation|AppRegistry|AppStateIOS|AsyncStorage|CameraRoll|InteractionManager|LinkingIOS|LayoutAnimation|NetInfo|PixelRatio|PushNotificationIOS|PanResponder|StatusBarIOS|StyleSheet|VibrationIOS|RCTDeviceEventEmitter|NativeModules|LinkedStateMixin|cloneWithProps|update/ ],
```

**Comment by mbrio** [comment]
That did it

**Comment by roman01la** [comment]
Thanks! I'll update with this.

**Comment by roman01la** [comment]
Updated both branches, also updated regexp in master with one extracted programatically in dep-graph branch.

**Comment by mxstbr** [comment]
I have the newest version with the updated regex, but I'm still getting the `Requiring unknown module "image!modern"` Error. I've added it to the `xassets` folder obviously, and the stack trace points to `__webpack_require__`, so I recon it's a problem webpack.

Any ideas?
