### ISSUE TITLE
Support for es6 classes

### ISSUE THREAD

**Issue by ahanriat** [roman01la/react-native-babel#3]
Hi Roman and thanks a lot for your really good job !

I've updated `babel-loader` to version `5.0.0` which allow me to use es6 classes. I don't know if there are limitation above that, but it currently works fine for me.

Best,

Antoine

**Comment by roman01la** [comment]
Ah, thanks, I'll update deps and check if everything is ok ;)

**Comment by jtremback** [comment]
What's the deal on this?
