### ISSUE TITLE
dep-graph branch- is it better?

### ISSUE THREAD

**Issue by jtremback** [roman01la/react-native-babel#7]

**Comment by jhabdas** [comment]
@jtremback I've been using the `webpack-watch` script in the `dep-graph` branch in my [React Native project](https://github.com/jhabdas/lumpen-radio). I prefer it to alternative approaches, which may require you to include a [mega-long RegExp](https://github.com/filp/react-native-es6-reflux/blob/master/ignored-modules.js). However, with abstraction comes additional complexity which may lead to issues as the community moves forward with ES2015+.
